### PR TITLE
fix: improve deno compatibility

### PR DESCRIPTION
**Pull request by idanran**

### CODE REVIEW

**Comment by idanran** [comment]
> We have no plans to upgrade supports-color to v9 as it breaks CJS users.
> 
> You may need to ask them to backport this change to v8.

I have changed to the CJS version of supports-color.

**Comment by shigma** [comment]
I don't like the idea of introduction forks to the project (same for #4).

In fact these low-level packages (object-inspect and supports-color) are dependent on a large number of packages, so there will be almost no overhead during installation. And once fork is introduced, it's almost a real volume increase.

I don't want to deny your efforts. On the contrary, since you have re-wrote so many packages, it doesn't seem too much to fork reggol as well. If you are not in a hurry, you can also wait for our follow-up updates. We will definitely release a **pure ESM** version in the future (maybe when node officially deprecates CJS or maybe even earlier).

**Comment by idanran** [comment]
> I don't like the idea of introduction forks to the project (same for #4).
> 
> In fact these low-level packages (object-inspect and supports-color) are dependent on a large number of packages, so there will be almost no overhead during installation. And once fork is introduced, it's almost a real volume increase.
> 
> I don't want to deny your efforts. On the contrary, since you have re-wrote so many packages, it doesn't seem too much to fork reggol as well. If you are not in a hurry, you can also wait for our follow-up updates. We will definitely release a **pure ESM** version in the future (maybe when node officially deprecates CJS or maybe even earlier).

Makes sense, I will close this PR. But jinpect (#4) is not a fork of object-inspect, and I think it would be a better choice than object-inspect in terms of functionality.

**Comment by idanran** [comment]
> And to note that the main reason why I don't want to make changes is that I have been too busy recently, and I am quite worried about breaking downstream after the merge. I do have future plans to investigate these changes, or even migrate directly to pure ESM. 😢



> And to note that the main reason why I don't want to make changes is that I have been too busy recently, and I am quite worried about breaking downstream after the merge. I do have future plans to investigate these changes, or even migrate directly to pure ESM. 😢

Hope all goes well and good night.

**Pull request closed without merging**
